export const Images = {
  primary: require('../assets/Images/primary.png'),
  home: require('../assets/Images/home.png'),
  search: require('../assets/Images/search.png'),
  heart: require('../assets/Images/Heart(6).png'),
  profile: require('../assets/Images/profileee.png'),
  profile_filled: require('../assets/Images/profilee.png'),
  heart_filled: require('../assets/Images/heart-color.png'),
  search_filled: require('../assets/Images/search-color.png'),
  home_filled: require('../assets/Images/home-color.png'),
  message: require('../assets/Images/list.png'),
  message_filled: require('../assets/Images/list-color.png'),
  payment_wallet: require('../assets/Images/paym.png'),
  back: require('../assets/Images/back.png'),
  trainer: require('../assets/Images/2.png'),
  trainer2: require('../assets/Images/3.png'),
  trainer3: require('../assets/Images/Mask.png'),
  filter: require('../assets/Images/filter.png'),
  notification: require('../assets/Images/notification.png'),
  messages: require('../assets/Images/message.png'),
  trainer4: require('../assets/Images/trainer4.jpg'),
};

export const FontFamily = {
  Extra_Bold: 'Manrope-ExtraBold',
  Bold: 'Manrope-Bold',
  Semi_Bold: 'Manrope-SemiBold',
  Medium: 'Manrope-Medium',
  Regular: 'Manrope-Regular',
  Light: 'Manrope-Light',
};
